[package]
name = "www-routes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
www-components.workspace = true

actix-web.workspace = true
maud.workspace = true
